//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade_Master
    {
        public string Grade_Code { get; set; }
        public string Description { get; set; }
        public int Min_Salary { get; set; }
        public int Max_salary { get; set; }
    }
}
